### ISSUE TITLE
Add more comment-formats for documentation

### ISSUE THREAD

**Issue by byaka** [devanonymous/docit#4]
Сейчас обрабатывается только один формат комментариев-описаний. Нужно расширить или добавить другие, например в flask не все комментарии обработались корректно, часть данных из них потерялась.

**Comment by shayna-ilya** [comment]
Имеется ввиду, что docit подхватывает коментарии только из двойных кавычек?

**Comment by byaka** [comment]
Нет, речь не об этом. Докстринг извлекается так

``` python
      # извлекаем общий комментарий
      if isModule(obj):
         docstr=strGet(inspect.getsource(obj), '"""\n', '\n"""') or ''
      else:
         docstr=inspect.getdoc(obj) or inspect.getcomments(obj) or ''
```

pydoc2api.py:152, для модуля действительно извлекается сейчас только по двойным ковычкам, для всего остального через питоновый инспект из байткода.

проблема в другом - PEP257 и сопутствующие документы не описывает конкретный формат каждой возможной секции (параметры, примеры, варнинги и т.д.), поэтому формат докстрингов отличается в разных проектах.
docit сейчас парсит формат типа [этого](https://github.com/byaka/flaskJSONRPCServer/blob/dev/flaskJSONRPCServer/__init__.py#L630) и [этого](https://github.com/byaka/flaskJSONRPCServer/blob/dev/flaskJSONRPCServer/__init__.py#L9). Этот формат покрывает многие проекты, но не все. Например есть еще [такой](http://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html) формат, который тоже распостранен. Его docit парсить не умеет.

**Comment by byaka** [comment]
This issue was moved to byaka/docit#5
